import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-[#F8F9E9]">
      <body className="font-mono">
        {children}
      </body>
    </html>
  );
}
